#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Книга-хуига  # The title of the book. Will be placed in the left navbar.
author                      : Семён Горбатый  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : figures/logo.png  # A path to the book logo

html:
  navbar_number_sections    : True  # Add a number to each section in your left navbar
